neo4j-devtools/relate

packages/common/src/system/system.provider.ts, packages/web/src/entities/project/graphql-upload.ts, packages/web/src/entities/project/project.resolver.ts
Fixes bug from https://github.com/neo4j-devtools/relate/pull/195 where uploads via graphql got corrupted due to `createReadStream` being called too early in the upload lifecycle.
Files uploaded via graphql corrupted
Files uploaded via graphql valid
no
=> Fix graphql-upload stream not complete

packages/cli/docs/dbms.md, packages/cli/src/commands/dbms/link.ts, packages/cli/src/commands/dbms/upgrade.ts, packages/cli/src/modules/dbms/upgrade.module.ts, packages/cli/src/modules/environment/api-token.module.ts, packages/common/src/utils/dbmss/dbms-upgrade-config.ts, packages/web/src/auth/services/auth.service.ts
- Fix the API token verification
- Pass the correct parameters to `dbms.upgrade` in the CLI module
- Use platform-independent paths when upgrading DBMSs
- Change the `--confirm` flag to boolean type on `dbms:link`
When verifying API tokens we use `req.hostname` as part of the token salt, which contains the origin URL in the format `<hostname>`, while when generating the tokens we use `<hostname>:<port>`. This means that currently all requests are rejected as unauthorized, even when they should be valid.
Tokens are now verified properly.
The `--confirm` flag on `dbms:link` is now a boolean instead of a string, so instead of calling the command as:
```
relate dbms:link <path> <name> --confirm=confirm
```
will have to be called as:
```
relate dbms:link <path> <name> --confirm
```
=> Use correct host URL when verifying API tokens

packages/web/src/auth/services/auth.service.ts, packages/web/src/index.ts
Enable CORS on web package and do a origin header string check. Similar change being added to bootstrapping of Relate module in Desktop
If origin is string 'null', currently being used as such. CORS not enabled.
CORS will be enabled and origin header of string 'null' will be handled correctly
=> enable cors and req.origin string null check

packages/common/package.json, packages/types/package.json
Documentation from the common and types packages is now added to the release commit.
`common` and `types` docs are not added to the release commit.
`common` and `types` docs are added to the release commit.
=> Add common and types docs when publishing

packages/web/src/auth/services/auth.service.ts
Bug fix.
When sending a request from a file, if the Origin header is `file://` instead of `null` the origin used to verify the token is an empty string. 
When sending a request from a file, if the Origin header is `file://` instead of `null` the origin used to verify the token defaults to Relate's HTTP origin. 
No.
=> Fix unauthorized requests when sending API requests from files

package.json, packages/cli/package-lock.json, packages/electron/package-lock.json, packages/web/package-lock.json
Bug fix
When releasing a new version, `@relate` package versions are bumped in all `package.json` files, but the corresponding `package-lock.json` files are left out of sync. Running `npm audit` after releases is then broken until the packages are synced again by manually running `npm install`.
When releasing a new version we fix the `package-lock.json` files after versions are bumped and before the package is published. The solution is described more in detail here: https://github.com/lerna/lerna/issues/1415#issuecomment-455790478
No
=> Fix package locks on publish

package.json, packages/cli/src/modules/app/app.e2e.ts, packages/cli/src/modules/app/open.module.ts, packages/client/src/utils.ts, packages/common/src/constants.ts, packages/common/src/entities/extensions/extensions.local.ts, packages/common/src/index.ts, packages/common/src/utils/extensions/get-app-base-path.ts, packages/common/src/utils/extensions/get-app-launch-url.ts, packages/common/src/utils/extensions/index.ts, packages/common/src/utils/generic/is-valid-url.ts, packages/electron/src/window/window.module.ts, packages/web/src/entities/extension/extension.constants.ts, packages/web/src/entities/extension/extension.e2e.ts, packages/web/src/entities/extension/extension.resolver.ts, packages/web/src/entities/extension/extension.types.ts, packages/web/src/entities/extension/extension.utils.ts
This PR adds support for using remote apps, defined as an installed STATIC extension whose `main` property contains a URL.
This PR also updates various URL parameters used by relate to match those of Neo4j Desktop, and exposes a new client utility for grabbing them from URLs.
Further this PR changes the GraphQL schema for apps to include a `url` property instead of a `path`.
Can only open locally installed apps
Apps can point to a URL
yes, this PR changes the GraphQL schema for apps to include a `url` property instead of a `path`.
Sample remote app:
```json
{
"name": "gewgle",
"version": "1.0.1",
"main": "https://google.com"
}
```
[extension-gewgle.zip](https://github.com/neo4j-devtools/relate/files/5458309/extension-gewgle.zip)
CLI Usage
```
$ relate app:open gewgle -L
> …
```
=> Feature remote STATIC extensions

scripts/tests/setup.js, scripts/tests/xvfb.sh
Allows tests to be run in Docker.
We can't run tests in Docker because the Electron tests hang indefinitely when no display server is available.
We can now call a script to setup up and teardown an in-memory display server that is needed to run Electron tests in Docker.
No
=> Add xvfb script for Docker tests

packages/cli/README.md, packages/cli/docs/app.md, packages/cli/docs/backup.md, packages/cli/docs/db.md, packages/cli/docs/dbms.md, packages/cli/docs/environment.md, packages/cli/docs/extension.md, packages/cli/docs/project.md, packages/cli/package.json, packages/cli/src/commands/dbms/info.ts, packages/cli/src/commands/dbms/install.ts, packages/cli/src/commands/dbms/upgrade.ts, packages/cli/src/commands/environment/use.ts, packages/cli/src/modules/dbms/info.module.ts, packages/cli/src/modules/dbms/install.module.ts, packages/cli/src/modules/dbms/upgrade.module.ts, packages/web/src/entities/dbms/dbms.resolver.ts, packages/web/src/entities/dbms/dbms.types.ts
Consistency and performance improvements.
- `infoDbmss` doesn't return the server status of DBMSs.
- Some CLI flags are camel case and some are kebab case.
- When passing the names or IDs of DBMSs to `dbms:info`, the status of each DBMS is retrieved twice.
- Links to the source code on the CLI are broken.
- `infoDbmss` now accepts an optional `onlineCheck` argument, and returns the server status of DBMSs.
- All CLI flags are now camel case.
- `dbms:info` always retrieves the info of DBMSs once.
- Links to the source code on the CLI are pointing to the right location.
Yes. All kebab case CLI flags have been converted to camel case. And `dbms:info` is not performing the online check by default.
=> Add server status to infoDbmss, make all CLI flags camel case

packages/common/src/entities/extensions/extensions.local.ts, packages/common/src/entities/extensions/install.test.ts, packages/common/src/utils/extensions/extension-versions.test.ts, packages/common/src/utils/system/test-extensions.ts, packages/web/src/entities/extension/extension.e2e.ts, packages/web/src/entities/extension/extension.resolver.ts
Replica of https://github.com/neo4j-devtools/relate/pull/152 (was created before the repo switch over and it seems to have lost context)
- have had to add filtering to check the the test extensions names include `path.basename(__filename)`, for example, as there didnt seem to be a guarantee of what can be in fixtures directory at any moment in time - was causing a lots of flaky test failures on builds otherwise.
=> common/extensions install and web/extensions.e2e tests

packages/cli/docs/project.md, packages/cli/src/commands/project/add-file.ts, packages/cli/src/modules/project/add-file.module.ts, packages/cli/src/modules/project/project.e2e.ts
Currently common and web packages allow for an overwrite param for project add file methods. This work gets the CLI up to date with these changes.
Cannot overwrite an existing project file with CLI package
Can now overwrite an existing file
no
=> add force flag for overwriting project files

packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/entities/projects/projects.local.ts, packages/common/src/utils/files/index.ts, packages/common/src/utils/files/is-symlink.ts
- add `is-symlink` util
- update `dbms.local` and `project.local` `link` methods to `unlink` if already a symlink. This is to allow relinking broken symlinks.
- updated `project` link to be in line with `dbms` link
If a dbms or project is already linked, and the target is moved, the symlink will remain and is broken. Project link also doesnt handle linking a previously linked Project (already has a manifest) in the same way as dbms
- When linking for project or dbms, when it already has a manifest and so previously linked, the presence of a symlink is checked and unlinked first. 
- Project link in line with dbms link now.
No, other than a discussion around a flag to prevent removing 'broken' links in the case when projects, for example, are loaded via storage device and not always …
=> add is-symlink check and update project and dbms link logic

packages/common/src/system/verifyAcceptedTerms.ts
- ensure `envPaths().data` exists before attempting to write the accepted terms
- added to `acceptTerms` as we use this in Desktop. Left `verifyAcceptedTerms` alone as where we call it in `system.provider`, we ensure dirs before
- attempt to write the accepted terms to the data path before ensuring it is there
- ensure data path before attempting to write
none
=> ensure global Relate data path exists before write file

.eslintrc.json, packages/common/src/entities/dbmss/install.test.ts, packages/common/src/entities/dbmss/link.test.ts, packages/common/src/entities/dbmss/manifest.local.test.ts, packages/common/src/index.ts, packages/common/src/utils/system/index.ts, packages/common/src/utils/system/test-environment.ts
Reduce flaky tests.
Tests are really flaky. Each time you run them a different test is failing, with either an error about a missing file or about invalid JSON when reading from a JSON file. 
A new util called `TestEnvironment` is now available to make test suites run in separate environments. This simplifies the teardown logic and reduces the chance of having different test suites interfering with each other. The intent is to later replace all uses of `TestDbmss` and `TestExtensions` with it.
No
=> Start running tests in separate environments

packages/cli/docs/project.md, packages/cli/src/commands/project/init.ts, packages/cli/src/commands/project/link.ts, packages/cli/src/modules/dbms/link.module.ts, packages/cli/src/modules/project/init.module.ts, packages/cli/src/modules/project/link.module.ts, packages/cli/src/modules/project/project.e2e.ts, packages/common/documentation/classes/dbmssabstract.md, packages/common/documentation/classes/projectsabstract.md, packages/common/src/entities/backups/backup.local.ts, packages/common/src/entities/dbmss/clone.test.ts, packages/common/src/entities/dbmss/dbmss.abstract.ts, packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/entities/dbmss/dbmss.remote.ts, packages/common/src/entities/dbmss/link.test.ts, packages/common/src/entities/environments/environment.local.ts, packages/common/src/entities/manifest/manifest.local.ts, packages/common/src/entities/projects/link.test.ts, packages/common/src/entities/projects/projects.abstract.ts, packages/common/src/entities/projects/projects.local.ts, packages/common/src/entities/projects/projects.remote.ts, packages/common/src/system/system.provider.ts, packages/common/src/utils/extensions/extension-versions.ts, packages/common/src/utils/system/test-extensions.ts, packages/types/documentation/classes/dict.md
Bug fixes and some minor features
- There is no way to unlink a project.
- `project.create` creates a project in some cases and links an existing project in other cases.
- `project.link` expects a manifest to exist.
- `projects.list` shows broken links as existing projects.
- Linking a DBMS/project containing a manifest with a duplicate name works, causing errors when trying to retrieve that entity.
- Linking a DBMS/project containing an invalid manifest works, causing errors later on when trying to retrieve that entity.
- Broken symlinks on Windows no prevent DBMSs/projects from being linked in the same location.
- added `projects.unlink` to unlink a linked project.
- `project.create` no longer links a project folder.
- `project.link` now creates the manifest if it doesn't exist.
- …
=> Refactor dbmss.link and projects.link

packages/common/src/constants.ts, packages/common/src/entities/environments/environment.constants.ts, packages/common/src/utils/dbmss/dbms-upgrade-config.ts, packages/web/package-lock.json, packages/web/package.json, packages/web/src/entities/dbms/dbms.e2e.ts, packages/web/src/entities/dbms/dbms.resolver.ts, packages/web/src/entities/dbms/dbms.types.ts, packages/web/src/entities/project/project.e2e.ts, packages/web/src/entities/project/project.resolver.ts, packages/web/src/entities/project/project.types.ts
Feature
- No way to set/remove metadata on DBMSs and projects.
- No way to add/remove tags on projects.
- No way to read existing metadata from DBMSs and projects.
- The import directory is not copied into new DBMSs during upgrades.
New mutations are available to:
- Set/remove metadata on DBMSs and projects
- Add/remove tags on projects
The `metadata` field is available on both DBMSs and projects.
The import directory is copied into new DBMSs during upgrades.
No
=> Add resolvers for getting/setting/removing metadata and tags

packages/cli/README.md, packages/cli/docs/project.md, packages/cli/src/commands/project/install-sample.ts, packages/cli/src/modules/db/load.module.ts, packages/cli/src/modules/project/install-sample.module.ts, packages/common/src/constants.ts, packages/common/src/entities/environments/environment.local.ts, packages/common/src/entities/environments/environment.remote.ts, packages/common/src/entities/projects/projects.abstract.ts, packages/common/src/entities/projects/projects.local.test.ts, packages/common/src/entities/projects/projects.local.ts, packages/common/src/entities/projects/projects.remote.ts, packages/common/src/index.ts, packages/common/src/models/index.ts, packages/common/src/models/project-install.model.ts, packages/common/src/utils/graphql.ts, packages/common/src/utils/system/get-manifest-name.ts
It introduces a new command `relate project:install-sample`, which grabs a list of Sample Projects from https://github.com/neo4j-graph-examples that are marked as `neo4j-approved` or some other filter that we decide on.
These projects contains sample data and also a new file (`relate.project-install.json`) that describes how Relate/Desktop should install Sample DBMSs and import sample data. See https://github.com/neo4j-graph-examples/northwind for an example.
The user will be prompted to install any DBMSs found under the dbms section in the file.
Note!
Currently the file is named `relate.project.json` in the northwind example. Because of this the second step doesn't work when testing the command.
(What changes might …
=> Install sample projects

packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/entities/environments/environment.local.ts, packages/common/src/entities/manifest/manifest.local.ts, packages/common/src/entities/projects/link.test.ts, packages/common/src/entities/projects/projects.local.ts, packages/web/src/entities/project/project.e2e.ts
Performance improvements
- When initializing an environment, all DBMS manifests in that environment are read.
- When linking a DBMS, all DBMS manifests are read.
- When getting a DBMS, all DBMS manifests are read.
- `resolveProjects` reads all project manifests to retrieve one project.
- No guards against multiple projects having the same name.
- Initializing an environment doesn't trigger any DBMS reads.
- Linking a DBMS gets a DBMS instead of listing all of them.
- When getting a DBMS, if the DBMS exists in memory, no manifests are read. Otherwise, all DBMS manifests are read.
- `resolveProjects` works as `resolveDbms` without reading any manifest.
- Projects behavior is now consistent with DBMSs in case of duplicate names. 
No
Further optimizations can be done, especially for projects, …
=> Reduce manifest reads

packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/entities/dbmss/link.test.ts
Bug fix
When linking (or in some cases upgrading) a DBMS that already contains the JWT plugin and the correct configuration for it, it is added again, making the DBMS unable to start.
When adding the security plugin, the options that are already properly configured are no longer modified.
No
=> Fix JWT plugin being added multiple times to DBMSs

packages/cli/src/modules/project/install-sample.module.ts, packages/common/src/entities/projects/projects.abstract.ts, packages/common/src/entities/projects/projects.local.ts, packages/common/src/entities/projects/projects.remote.ts, packages/common/src/models/project-install.model.ts
This addresses an issue where sample projects couldn't be downloaded when the default branch had been renamed from master to something else.
This is a fix for installing Sample projects. It changes the assumption that the default branch of a repo at `neo4j-graph-examples` is `master` and now instead uses `default_branch` from the GitHub API to determine the download URL.
`master` is hardcoded in the download URL.
=> Fix downloading of sample projects.

packages/common/src/constants.ts, packages/common/src/entities/dbms-plugins/dbms-plugins.abstract.ts, packages/common/src/entities/dbms-plugins/dbms-plugins.local.test.ts, packages/common/src/entities/dbms-plugins/dbms-plugins.local.ts, packages/common/src/entities/dbms-plugins/dbms-plugins.remote.ts, packages/common/src/entities/environments/environment.abstract.ts, packages/common/src/entities/environments/environment.constants.ts, packages/common/src/entities/environments/environment.local.ts, packages/common/src/entities/environments/environment.remote.ts, packages/common/src/models/dbms-plugin.model.ts, packages/common/src/utils/dbms-plugins/discover-plugins.ts
Fixed the implementation for plugin sources to follow the [DBMS plugins RFC](https://github.com/neo4j-devtools/relate/blob/5af3f9d4b9360c26576cfc7414b26a79807c4cfb/documentation/RFCs/dbms-plugins/dbms-plugins.rfc.md).
- List sources only from the file system
- Adding sources requires a list of URLs to indirection files, each containing one or more sources
- Get default sources from [neo4jlabs-plugins.json](https://raw.githubusercontent.com/neo4j/docker-neo4j/master/neo4jlabs-plugins.json), and user sources from the file system
- Adding sources requires a list of `IDbmsPluginSource` objects each representing a single source
- More edge cases covered
Yes, the implementation and interface for plugin sources are changed.
=> Fix dbms plugin sources implementation

packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/entities/dbmss/info.test.ts, packages/common/src/utils/system/test-environment.ts
Bug fix
If the DBMS config is changed to use different ports while the application is running, the `dbmss.info` method will always return `serverStatus === "offline"` (when performing the online check). This is because we read the DBMS config once, before it's changed, and perform the check against the ports specified there.
Add tests for `dbmss.info` and read the config before checking if the DBMS is online.
No
=> Fix dbms.info always returning "offline" when changing ports

packages/common/src/entities/dbms-plugins/dbms-plugins.local.test.ts, packages/common/src/entities/environments/environment.constants.ts
Refactoring
- The URL for official plugin sources is pointing to the file used by the Neo4j docker image. 
- Calls to the official plugin sources URL are mocked in the e2e tests.
- The URL for official plugin sources is pointing to a [file](https://dist.neo4j.org/relate/official-plugin-sources.json) we're hosting on S3. 
- Calls to the official plugin sources URL are not mocked in the e2e tests.
No
=> Update sources list URL and remove mocks on e2e tests

packages/cli/docs/environment.md, packages/cli/src/commands/environment/init.ts, packages/cli/src/modules/dbms/upgrade.module.ts, packages/cli/src/modules/environment/environment.local.e2e.ts, packages/cli/src/modules/environment/init.module.ts
API improvement
In order to get started with Relate, new users need to: 
- Run the `env:init` command, reply to prompts about configuration options that might not be relevant to them, or that they might not understand.
- Run the `env:use` command, to set the newly created environment as active.
- If the user doesn't have Desktop installed, they'll also have to either install Java on their machine or download it and extract it in Relate's cache.
In order to get started with Relate, new users need to: 
- Run `relate env:init <environmentName> --use`
Default values will be used for configuration and Java will be automatically downloaded in Relate's cache if it's not already present. Also with the `--use` flag, the environment just created will also be set as active. 
For advanced users the …
=> CLI: simplify environment initialization

packages/common/src/entities/dbms-plugins/dbms-plugins.local.ts, packages/common/src/models/dbms-plugin.model.ts, packages/common/src/utils/dbmss/dbms-upgrade-config.ts
Update types/feature
- Plugins are downloaded on each install
- Homepage URLs are mandatory for version objects 
- Plugins are cached in the same way DBMSs and other entities are cached
- Homepage URLs are optional for version objects
No
=> Cache downloaded DBMS plugins

packages/common/src/index.ts, packages/common/src/models/dbms-plugin.model.ts
exports a couple of constants and utils specific to plugins (needed in Desktop). Also changes `IDbmsPluginUpgradable upgradable` property type to be `IDbmsPluginVersion` and not `IDbmsVersion`
exports and constants not exported and `IDbmsVersion` type described causing issues.
exports constants and utils required in Desktop and changes type described above.
No
=> Plugins - export Desktop required plugin utils, consts

packages/common/package-lock.json, packages/common/package.json, packages/common/src/entities/dbms-plugins/dbms-plugins.local.ts, packages/common/src/system/files/ensure-files.test.ts, packages/common/src/utils/dbmss/dbms-versions.ts, packages/common/src/utils/extensions/extension-versions.ts, packages/electron/package-lock.json, packages/electron/package.json, packages/web/package-lock.json, packages/web/package.json
Updates  `@types/fs-extra` so we can have uniform usage of `fse` without resorting to `fs` for `readdir`
Had to use `fs.readdir` to pass in valid options object
Can now replace `fs.readdir` with `fse.readdir`
No
=> update @types/fs-extra and remove fs use for readdir

packages/cli/src/modules/db/dump.module.ts, packages/common/src/constants.ts, packages/common/src/entities/environments/environment.local.ts, packages/common/src/utils/dbmss/upgrade-neo4j.ts
Adds a new directory in the relate data dir (`upgrade-logs`) that copies the logs from the DBMS failed to upgrade.
A new folder called `upload-logs` is created in the relate storage dir. Whenever an upgrade fails, the logs from the failed upgrade are copied into this directory to help users debug.
The failed upgrade neo4j directory is just deleted, removing all logs too. Leaving users without the logs for help when debugging.
Logs of failed upgrades are kept instead of deleted.
=> Store logs for failed upgrades

packages/common/package-lock.json, packages/common/package.json
Similar to https://github.com/neo4j-devtools/relate/pull/285
Updated to official release of neo4j-driver-lite
Not much different to `rc` version used currently
Same as before
No
Tested for 4.2.x and 4.3 DBMSs - works as expected. Tested with 3.5.17 and thats fails as expected (for access-token and db operations)
=> neo4j-driver-lite 4.3 official release driver bump

packages/cli/docs/dbms.md, packages/cli/src/commands/dbms/stop.ts, packages/cli/src/modules/dbms/stop.module.ts, packages/common/src/constants.ts, packages/common/src/entities/dbms-plugins/dbms-plugins.local.test.ts, packages/common/src/entities/dbmss/dbmss.abstract.ts, packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/entities/dbmss/dbmss.remote.ts, packages/common/src/entities/dbs/dbs.local.ts, packages/common/src/models/dbms.model.ts, packages/common/src/utils/dbmss/dbms-stop.ts, packages/common/src/utils/dbmss/is-dbms-online.ts, packages/common/src/utils/dbmss/system-db-query.ts, scripts/tests/setup.js, scripts/tests/teardown.js
Feature
DBMSs are stopped only through the Neo4j scripts or in the case of Windows they are forcefully terminated.
DBMSs can now be stopped through the shutdown procedure by passing the connection details to the stop function instead of the name or ID of the DBMSs. This will allow gracefully stopping the DBMS on Windows.
No
=> Allow stopping DBMSs through shutdown procedure

packages/cli/src/modules/dbms/info.module.ts, packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/models/dbms.model.ts, packages/common/src/utils/dbmss/cypher-shell.ts, packages/common/src/utils/dbmss/dbms-versions.ts, packages/common/src/utils/dbmss/neo4j-admin-cmd.ts, packages/common/src/utils/dbmss/neo4j-cmd.ts, packages/common/src/utils/dbmss/neo4j-process-win.ts, packages/web/src/entities/dbms/dbms.types.ts
Bug fix
It's not possible to install Neo4j distributions that contain a prerelease label in the version (eg. `4.3.0-preview`).
It's now possible to install prerelease versions of Neo4j, and the DBMS info now contains a new optional attribute containing that prerelease label.
No
To try this, download the 4.3.0-preview archive from [here](https://neo4j.com/download-center/#enterprise) and then run:
```
relate dbms:install ./neo4j-enterprise-4.3.0-preview-[platform].tar --name 43preview
```
Or after extracting the archive:
```
relate dbms:link ./neo4j-enterprise-4.3.0-preview 43preview
```
=> Allow installing prerelease versions of the DBMS

package-lock.json, package.json, packages/cli/package.json, packages/cli/src/modules/db/dump.module.ts, packages/cli/src/modules/dbms/dbms.e2e.ts, packages/common/package.json, packages/common/src/utils/dbmss/spawn-promise.ts, packages/electron/package.json, packages/web/package.json
Bug fix
- Arguments for the Neo4j scripts are not escaped properly on Windows leading to errors when trying to use paths containing spaces. 
- The `db:dump` command doesn't show the actual error message if the operation fails. 
- Package locks are not updated automatically when releasing.
- Arguments are now escaped properly, allowing the use of paths with spaces. 
- `db:dump` will show all output from the Neo4j script.
- Package locks should update automatically when releasing.
No
=> Escape arguments properly on Windows DBMS scripts 

package.json, packages/cli/package.json, packages/common/package.json, packages/electron/package.json, packages/web/package.json
Revert commit https://github.com/neo4j-devtools/relate/pull/312/commits/1fd26d52034ddb4814020cba9d66b3cdad9de470 that addresses package locks not updating automatically on releases. The fix didn't actually work and I'll have to spend some more time to find out a better solution.
No
=> Revert fix for automatically updating package locks

packages/common/package-lock.json, packages/common/package.json, packages/common/src/entities/dbms-plugins/dbms-plugins.local.ts, packages/common/src/utils/dbmss/download-neo4j.test.ts, packages/common/src/utils/dbmss/download-neo4j.ts, packages/common/src/utils/download.ts, packages/common/src/utils/extensions/download-extension.ts, packages/common/src/utils/index.ts
Bug fix
Recent versions of hasta don't play well with Electron, so when verifying a shasum (after downloading a plugin/DBMS/extension) on a packaged Electron app the method generating the hash hangs indefinitely.
To generate the hash of downloaded files we now use the core crypto module instead of hasha. 
No
=> Replace hasha with crypto for sha256 check

packages/common/src/entities/dbs/dbs.constants.ts, packages/common/src/entities/dbs/dbs.local.ts
DB names can have hyphens but currently relate prevents that. This fixes that.
DB names are checked for invalid chars, which currently includes hyphens.
Allows hyphens and wraps the DB name with backtiks when creating.
=> Allow a DB name to include hyphens

packages/common/src/utils/dbmss/neo4j-process-win.ts
Bug fix
The DBMS starter script is copied only when it doesn't already exist, this means that any changes we make to it will not be applied on upgrades of Relate, unless the script in the cache is manually deleted. 
The DBMS starter script is copied every time a DBMS is started on Windows. This way we ensure it's always up to date. 
No
=> Always copy DBMS starter PowerShell script when starting DBMSs

packages/common/src/utils/dbmss/neo4j-process-win.ts
Revert overwriting the PowerShell script used to start DBMSs.
No
This change is temporary until we find a better way to distribute the signed PowerShell script, and until we have a better solution for running this script in environments where background PowerShell processes are not allowed.
=> Revert overwriting of neo4j-start.ps1 when starting DBMSs

packages/cli/docs/environment.md, packages/cli/src/commands/environment/list.ts, packages/types/package-lock.json, packages/types/package.json
Fix docs generation and add new flags to `env:list`.
- Generating new docs for the types package is failing because of breaking changes in the upgraded typedoc version.
- The `env:list` CLI command doesn't accept any flags.
- Reverted to the previously working version of typedoc. 
- The `env:list` CLI command now accepts the same table flags as the other list commands (eg. filter, output, sort).
No
=> Revert typedoc upgrade, add table flags to env:list command

packages/electron/src/configs/dev.config.ts, packages/web/src/configs/dev.config.ts, packages/web/src/web.module.ts
Add an option in the WebModule config for setting the `autoSchemaFile` value in the GraphQLModule.
GraphQL schemas are always generated and stored in memory. 
The WebModule can now be configured to generate the schema locally if needed (eg. for verifying queries with eslint-plugin-graphql).
No
=> Add autoSchemaFile option to WebModule config

packages/common/src/constants.ts, packages/web/src/entities/dbms-plugins/dbms-plugins.e2e.ts, packages/web/src/entities/dbms-plugins/dbms-plugins.module.ts, packages/web/src/entities/dbms-plugins/dbms-plugins.resolver.ts, packages/web/src/entities/dbms-plugins/dbms-plugins.types.ts, packages/web/src/entities/dbms-plugins/index.ts, packages/web/src/web.module.ts
Added resolvers and tests for the following `dbms-plugin` operations:
- `add-sources`
- `list-sources`
- `remove-sources`
- `install`
- `list`
- `uninstall`
No resolvers or tests for and `dbms-plugins` operations 
Can now list/add/remove dbms-plugins and sources.
no
=> dbms-plugins resolvers and tests added

packages/common/src/constants.ts, packages/web/src/entities/dbms/dbms.e2e.ts, packages/web/src/entities/dbms/dbms.resolver.ts, packages/web/src/entities/dbms/dbms.types.ts, packages/web/src/entities/extension/extension.e2e.ts
Added resolver and test for `dbms.upgrade`
No resolver for `dbms.upgrade`
Can now upgrade dbmss via the web package
no
Have had to mould the test dbms install slightly to get it to work as I am not sure what is causing an issue for me at the moment. Will look at the end if I have time.
=> added dbms upgrade resolver and tests

packages/cli/src/modules/project/install-sample.module.ts, packages/common/src/models/project-install.model.ts
Checks the `relate.project-install.json` file for `dbms -> plugins[]` which is an array of plugin IDs, if found the plugins are installed after the sample dbms has been created. 
Plugins are not installed for sample projects.
Plugins are installed for sample projects.
No
=> Install plugins after creating a sample dbms.

.eslintrc.json, packages/common/src/entities/dbms-plugins/dbms-plugins.local.test.ts, packages/web/src/entities/dbms/dbms.resolver.ts, packages/web/src/entities/dbms/dbms.types.ts, packages/web/src/utils/file-watcher.utils.ts
- adds debounce to the file event handler
- publish for DBMS install/uninstall events
- return structure is different, with a property for each event type (see screenshots)
- Note - currently can only return the DBMS ID when an uninstall occurs since that is the only info we would have from Chokidar and so cannot use `dbmss.info` after this point with this DBMS ID (since its deleted).
- DBMS install / uninstall will publish any new events for the subscription resolver
- New structure with DBMS install / uninstall published 
Yes - when introduced we would need to make adjustments wherever the `watchInfoDbmss` subscription has been used -  Desktop 2.0 and the Sample App.
=> Modify watchInfoDbmss subscription to account for DBMS install/uninstall

packages/common/src/utils/dbmss/upgrade-neo4j.ts
Feature
If a DBMS folder is locked, the DBMS upgrade process fails midway through. An `EBUSY` error is thrown. The catch block tries to clean up but runs into problems:
- uninstalling the DBMS errors, and that error is swallowed
- moving the restored DBMS to the original folder errors `dest already exists` and that error is returned => so the original error is lost
No information on what happened is logged out.
- The upgrade process begins by trying to open the DBMS folder. If that isn't possible, the upgrade is aborted and a clear error message is returned, explaining either that the file is locked (if the error is `EBUSY`), or cannot be opened
- The catch/cleanup block emits a DEBUG event so that we never completely lose the error even if the cleanup fails
- The uninstall DBMS lines in …
=> Improve upgrade error logging

packages/web/src/auth/auth.module.ts, packages/web/src/auth/middleware/api-token.middleware.ts, packages/web/src/auth/middleware/auth-token.middleware.ts, packages/web/src/auth/services/auth.service.ts
Bug fix
Token handlers are registered during the application initialization (they are express middleware functions), but there is no guarantee that they are registered before the routes. This can cause the routes that are initialized before the handlers to not require authentication when they should. I haven't noticed this happening when running `@relate/web` on its own, but I noticed it happening in certain cases when extending the WebModule. 
Token handlers are registered using Nestjs middleware, ensuring that they are always registered before any route.
No.
Removes auth for the GraphQL Playground and Swagger API docs. Auth is still needed to be able to fetch types for the autocompletion and docs, but at least it's now possible to load the main interface and pass the token and client ID …
=> Use NestMiddleware to register token handlers

packages/cli/src/modules/project/install-sample.module.ts, packages/common/src/entities/projects/projects.abstract.ts, packages/common/src/entities/projects/projects.local.ts, packages/common/src/entities/projects/projects.remote.ts
Allows for `dumpFile` or a `scriptFile` in the sample project dbms description to point to a URL instead of a local file. The file will be downloaded before it is imported.
Also removes `got` for `listSampleProjects` and uses `requestJson` instead, which should work with the Desktop proxy. 
Currently only local files can be defined.
=> Allow URLs for Sample Project dumps and scripts

.github/workflows/pull-request.yml, .github/workflows/setup/action.yml, package.json
Fix the way we run tests.
The e2e tests are getting stuck in a loop trying to execute the `test` script from the root level of the repo. This issue only shows up in the release pipeline and not in the PR tests, likely because the pnpm versions used in the two actions are different. 
All actions are using the same version of pnpm and we filter out the root `test` script when calling `pnpm --recursive test` to avoid an infinite loop. 
No
=> Fix e2e tests script and Github action

.changeset/blue-foxes-tan.md, .github/workflows/release.yml, packages/web/package.json, pnpm-lock.yaml
Currently, the release action is failing because NPM can't detect the token used for publishing. This PR follows the [official docs](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#set-the-token-as-an-environment-variable-on-the-cicd-server) to configure NPM to get the token from the NPM_TOKEN environment variable.
Fix the server in @relate/web not starting because of a missing dependency.
Create changeset for the 5.0 initial support changes.
No
=> Fix NPM auth on release action

.changeset/mean-stingrays-do.md, .changeset/odd-pants-develop.md, packages/cli/src/modules/dbms/install.module.ts, packages/common/package.json, packages/common/src/entities/dbmss/dbmss.abstract.ts, packages/common/src/entities/dbmss/dbmss.local.ts, packages/common/src/utils/dbmss/dbms-versions.test.ts, packages/common/src/utils/dbmss/dbms-versions.ts, packages/common/src/utils/dbmss/download-neo4j.ts, pnpm-lock.yaml
5.0.0-drop0X.0 are causing issues with version checks when downloading, this fixes those issues.
This change version checks to allow `drop0X.0` prereleases to be downloaded. 
`drop0X.0` version checks fail to download with an error.
`drop0X.0` versions are downloaded and installed successfully.
=> Allow 5.0.0 drops to be dowloaded

.github/workflows/release.yml, package.json
The changeset action is currently not working because it's running the script in the `version` variable as one command and we need to run two commands, one for bumping the package versions, and one for re-generating the docs.
https://github.com/neo4j-devtools/relate/runs/8017704687?check_suite_focus=true#step:4:26
No
=> Fix version script on release action

packages/common/src/entities/dbs/dbs.local.ts
Allow hyphens in db name when doing a DROP DATABASE
Relate fails to drop a db containing a hyphen
Relate succeeds when dropping a db containing a hyphen
--
See issue #397
=> Allow hyphens in db name when doing a DROP DATABASE

.github/workflows/release.yml, .gitignore
Git can't ignore a tracked file, so the change from #420 is not working. This results in the release pipeline still failing because the working is unclean after we update the .npmrc file. 
This PR reverts ignoring the .npmrc file (which didn't work) and updates the release action to modify the user npm config instead of the local one. 
No
=> Update global .npmrc instead of local one on release action

.changeset/large-poets-fail.md, .github/workflows/cla-check.yml, packages/web/src/entities/dbms/dbms.resolver.ts, packages/web/src/entities/dbms/dbms.types.ts
- `infoDbmss` no longer requires an array of IDs, and when no ID is provided we return the entire list of DBMSs and their status. This is to avoid having to send two separate requests for getting the status of all DBMSs.
- `watchDbmss` now sends events for STARTED and STOPPED **after** we confirmed that the Neo4j server status is online or offline. The previous behavior would react to the change in the file system and send whatever status we had at the time the change happened. That could result for example in a STARTED event being created after the DBMS process started (the PID file was created) but before the server was online.
No
=> Tweak watchDbmss to observe changes in the server status rather then the process status

.changeset/cool-vans-change.md, packages/common/src/entities/environments/environment.constants.ts, packages/common/src/utils/dbmss/dbms-upgrade-config.ts, packages/common/src/utils/dbmss/upgrade-neo4j.ts
* Bump supported version to 4.1
* Prevent Neo4j 4 -> 5 upgrades.
* Don't run migration step for 5.0 upgrades.
=> Neo4j 5.x upgrade fixes.

.changeset/loud-beans-burn.md, packages/common/src/utils/dbmss/resolve-java.ts
Allow `arm64` java dists for Apple Silicon to be downloaded.
`arm64` dists are blocked from being downloaded.
=> fix(relate): allow apple silicon dists to be downloaded
