neo4j-devtools/relate

packages/cli/package.json

Add CLI docs to the release commit when publishing a new version.
CLI docs are not added to the release commit.
CLI docs are added to the release commit.
No.

Add CLI docs when publishing

---

packages/cli/package-lock.json
packages/common/package-lock.json
packages/common/package.json
packages/web/package-lock.json

Bump some dependencies and fix package-lock files with correct versions of Relate.

Bump dependencies

---

packages/common/src/entities/environments/environment.constants.ts

Bump version of the Zulu JVM fetched by Relate.
No

Update Java version fetched by Relate

---

documentation/RFCs/relate-client/relate-client.rfc.md

Proposes a frontend client library for allowing apps to interact with `@relate`
See [RFC doc](https://github.com/huboneo/relate/blob/rfc-relate-client/documentation/RFCs/relate-client/relate-client.rfc.md) for latest version 
See [Spike PR](https://github.com/neo4j-devtools/relate/pull/13) for example usage

Rfc relate client

---

.eslintrc.json
packages/cli/src/modules/db/load.module.ts
packages/cli/src/modules/environment/init.module.ts
packages/cli/src/prompts/select.prompt.ts
packages/common/src/constants.ts
packages/common/src/entities/dbmss/dbmss.local.ts
packages/common/src/entities/environments/environment.abstract.ts
packages/common/src/system/system.provider.ts
packages/common/src/utils/dbmss/cypher-shell.ts
packages/common/src/utils/system-access-token.ts
packages/common/src/utils/system/test-dbmss.ts
packages/web/src/auth/services/auth.service.ts

This PR saves access tokens to separate files to avoid race-conditions when multiple processes are trying to create them at the same time
Concurrent tests fail due to overwrites
Concurrent tests pass

Chore separate access token files

---

packages/common/src/constants.ts
packages/common/src/entities/backups/backup.local.ts

Cleaned up backup.local implementation

---

packages/common/documentation/README.md
packages/common/documentation/classes/backupabstract.md
packages/common/documentation/classes/dbmssabstract.md
packages/common/documentation/classes/dbsabstract.md
packages/common/documentation/classes/environmentabstract.md
packages/common/documentation/classes/extensionsabstract.md
packages/common/documentation/classes/manifestabstract.md
packages/common/documentation/classes/projectsabstract.md
packages/common/package-lock.json
packages/common/package.json
packages/types/documentation/README.md
packages/types/documentation/classes/bool.md
packages/types/documentation/classes/dict.md
packages/types/documentation/classes/list.md
packages/types/documentation/classes/maybe.md
packages/types/documentation/classes/monad.md
packages/types/documentation/classes/nil.md
packages/types/documentation/classes/none.md
packages/types/documentation/classes/num.md
packages/types/documentation/classes/str.md
packages/types/documentation/interfaces/imonad.md

Update docs and bump code-signer

---

packages/common/src/entities/projects/projects.local.ts

Updates the Sample Graph URL to use the GitHub Search API.
Uses the `/orgs/{ORGANISATION}/repos` endpoint.
We now filter on the topic `neo4j-approved`.

Use GitHub APIs search endpoint.

---

packages/common/src/constants.ts
packages/common/src/entities/dbms-plugins/dbms-plugins.local.test.ts
packages/common/src/utils/dbms-plugins/list-sources.ts
packages/common/src/utils/dbms-plugins/list-versions.ts
packages/common/src/utils/dbmss/dbms-versions.ts
packages/common/src/utils/dbmss/download-neo4j.ts
packages/common/src/utils/download.ts
packages/common/src/utils/extensions/download-extension.ts
packages/common/src/utils/extensions/extension-versions.ts

Feature
Relate requests and downloads are not customizable.
Requests for listing and downloading versions can now be overridden by registering a hook actor. 
No

Allow custom request/download methods

---

packages/cli/package-lock.json
packages/client/package-lock.json
packages/common/package-lock.json
packages/electron/package-lock.json
packages/types/package-lock.json
packages/web/package-lock.json

Fix package locks
Package locks contain older versions of the Relate packages. 
Versions on the package locks match the ones in the latest Relate release.
No
Seems like TeamCity is still not updating the package locks with the new Relate versions when publishing Relate. This needs more investigation.

Fix package locks

---

documentation/DBMS_PLUGINS.md
documentation/NEO4J_ON_WINDOWS.md

Update Neo4j on Windows docs, add DBMS plugins docs

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/base.command.ts
packages/common/package-lock.json
packages/common/package.json
packages/electron/package-lock.json
packages/electron/package.json
packages/web/package-lock.json
packages/web/package.json

The peer dependency on @relate/types was accidentally pinned to a specific version on @relate/common, which is now preventing the other packages to bump @relate/types to the latest version. This PR reintroduces the range that was previously in place.
No
A release is required to be able to propagate these changes to the other packages.

Fix common package peer dependency

---

packages/common/src/entities/dbmss/dbmss.local.ts

Adds `dbms.jvm.additional=-Dlog4j2.formatMsgNoLookups=true` to the config to protect users from the Log4j 0-day exploit.
Log4j has a 0-day exploit which is present in Neo4j 4.2.x and up. To help protect users we automatically add the setting `dbms.jvm.additional=-Dlog4j2.formatMsgNoLookups=true` to the users `neo4j.conf` before starting the DBMS.
x
x
x
Quote from Jonatan Jäderberg regarding adding this to every DBMS:
"It is conceivable that some enterprise customer somewhere is actually using this as a feature--i.e., they have some LDAP server with Java code that they want to be involved in their logging.
If that's the case, their particular use case could break.
But in the interest of helping the vast vast majority of users stay safe, I think that's worth it
They can easily override this …

Log4j 0-day exploit fix

---

packages/common/src/entities/projects/projects.local.ts

Some sample projects where missing from the listing because they are forks. This fixes that.
Forks are not listed.
Forks are also listed.

Show forks in sample project list.

---

.github/workflows/pull-request.yml
package.json

Configure GitHub actions to run e2e tests on PRs.
No.

Add Github actions PR tests

---

renovate.json

Exclude typescript and nestjs dependencies from the bulk minor/patch upgrade PR that renovate creates.
No

Update renovate upgrade groups

---

packages/cli/src/modules/environment/init.module.ts
packages/common/src/entities/environments/environment.constants.ts
packages/common/src/utils/dbmss/dbms-versions.ts
packages/common/src/utils/dbmss/resolve-java.ts

Adds support for Neo4j 5.0 by adding Java 17.
Currently we only use Java 8 and 11
Adding Java 17 to the list of versions

Neo4j 5.0 Support

---

.github/workflows/release.yml

Configure the release action to use the NPM token from the release environment. 
No

Use NPM token from GHA environment

---

.github/workflows/release.yml
renovate.json

Github actions are not run on pull requests created by the Github actions bot, so we need a PAT to be able to run tests before merging the release PR created by changesets. https://github.com/orgs/community/discussions/25602 
No

Use Github PAT to generate release PR

---

.changeset/grumpy-elephants-begin.md
.github/workflows/release.yml
.npmrc
package.json
packages/common/package.json
pnpm-lock.yaml

- Bump `@neo4j/code-signer`.
- Update the release script. The current script is not publishing packages in the right order, so it fails when publishing multiple packages that depend on one another.
No

Bump code signer package

---

.changeset/slow-walls-teach.md
e2e/jest-global.setup.js
packages/cli/docs/dbms.md
packages/cli/src/commands/dbms/upgrade.ts
packages/cli/src/modules/db/db.e2e.ts
packages/cli/src/modules/dbms-plugin/dbms-plugin.e2e.ts
packages/common/src/entities/dbms-plugins/dbms-plugins.local.test.ts
packages/common/src/entities/dbmss/dbmss.local.ts
packages/common/src/entities/dbmss/upgrade.test.ts
packages/common/src/index.ts
packages/common/src/utils/dbmss/upgrade-neo4j.ts
packages/common/src/utils/system/test-dbmss.ts
packages/common/src/utils/system/test-environment.ts
packages/web/package.json
packages/web/src/entities/db/db.e2e.ts
packages/web/src/entities/dbms-plugins/dbms-plugins.e2e.ts
packages/web/src/entities/dbms/dbms.e2e.ts
packages/web/src/entities/dbms/dbms.resolver.ts
packages/web/src/entities/dbms/dbms.types.ts
pnpm-lock.yaml
scripts/tests/setup.js

- Update e2e tests to use more recent versions of Neo4j.
All version of Neo4j we're testing against are unsupported.
Most of the versions we're testing against are supported. There are some exceptions on the DBMS upgrade tests because we have no other way to test major upgrades without resorting to installing 3.5.
No.

Run e2e tests against supported versions of Neo4j

---

.github/workflows/release.yml
packages/cli/src/modules/db/list.module.ts
packages/common/src/entities/dbmss/dbmss.local.ts
packages/common/src/entities/dbs/dbs.abstract.ts
packages/common/src/entities/dbs/dbs.local.ts
packages/common/src/entities/environments/environment.constants.ts
packages/common/src/models/dbms.model.ts
packages/web/src/entities/db/db.resolver.ts

The result from the SHOW DATABASES command has changed and this addresses that.
The result for `SHOW DATABASES` has changed in 5.*, this PR adds support for that.
Currently the result only supports 4.*.
Support for both 4.* and 5.*.
-

Adjust list DBs result.

---

.gitignore
.husky/pre-push

Gitignore the .npmrc file that is modified during the release process, and remove the git hook for running e2e tests on push.
The release pipeline is failing to create the publish commit because the working directory is unclean after we update the npmrc file.
No

Gitignore .npmrc file

---

.changeset/six-onions-crash.md
packages/common/src/constants.ts
packages/web/src/entities/dbms/dbms.resolver.ts
packages/web/src/entities/dbms/dbms.types.ts

Adds a mutation for linking a local dbms path

Add link dbms mutation

---

.changeset/heavy-games-yell.md
.github/workflows/setup/action.yml
package.json
packages/cli/package.json
packages/client/package.json
packages/common/package.json
packages/types/package.json
packages/web/package.json
pnpm-lock.yaml

This package is no longer needed as of [Nest.js v5.0.0](https://github.com/nestjs/nest/releases/tag/v5.0.0).

Remove reflect-metadata

---

.changeset/large-donuts-sniff.md
packages/cli/src/modules/dbms/open.module.ts
packages/cli/src/modules/environment/open.module.ts
packages/cli/src/modules/project/open.module.ts

Importing the "open" package isn't working because it is now an ESM only module. This PR updates references to this package to be imported correctly.

Fix import of ES module open
